#!/bin/bash

# Remove modification to user's path. Leave lein installed.

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function remove-path {
  if [[ -e $HOME/$1 ]]; then
    sed -i -e '/clojure-hub/d' ~/$1
  fi
}

remove-path .bash_profile
remove-path .bashrc
